# vim:ft=kitty

## name: Aquarium Dark
## license: MIT
## author: Frenzy
## upstream: https://github.com/FrenzyExists/aquarium-vim/raw/vimscript-version/extras/kitty_aquarium_dark.conf
## It's always first light then dark

foreground            #A7B7D6
background            #20202a
selection_foreground  #2C2E3E
selection_background  #E5E9F0
url_color             #B8DEEB

# black
color0                #20202a
color8                #1a1a24

# red
color1                #Ebb9b9
color9                #EAC1C1

# green
color2                #B1DBA4
color10               #A3CCAD

# yellow
color3                #E6DFB8
color11               #e6dfb8

# blue
color4                #6A8CBC
color12               #63718B

# magenta
color5                #F6BBE7
color13               #b294bb

# cyan
color6                #CDDBF9
color14               #95C2D1

# white
color7                #CDDBF9
color15               #E6E6F1

# Cursor
cursor                #b8dceb
